### ISSUE TITLE
Error: Cannot find CapError exception

### ISSUE THREAD

**Issue by llouw** [robertwitt/cap-remote-service-rest#8]
https://github.com/robertwitt/cap-remote-service-rest/blob/b0580f66a61782bc7a612a57bb1b853ce0bc2dcf/lib/path.js#L28

When I ran the package with an imported API it threw an error that it couldn't find `CapError`.

Add `const { CapError} = require('./error')` to the top `path.js`.

**Comment by robertwitt** [comment]
Published a new [version](https://www.npmjs.com/package/cap-remote-service-rest) with this fix.
